# Generated by Django 4.2.6 on 2023-11-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0005_alter_book_publication_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.CharField(
                blank=True,
                default="https://upload.wikimedia.org/wikipedia/commons/3/3f/Placeholder_view_vector.svg",
                max_length=255,
                null=True,
            ),
        ),
    ]
