# Generated by Django 4.2.6 on 2023-11-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0006_alter_book_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="ISBN",
            field=models.CharField(max_length=20),
        ),
    ]
