# Generated by Django 4.2.6 on 2023-11-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0008_alter_book_options_bookloan"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={},
        ),
    ]
