# Generated by Django 4.2.6 on 2023-10-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_alter_book_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.CharField(
                default="https://upload.wikimedia.org/wikipedia/commons/3/3f/Placeholder_view_vector.svg",
                max_length=255,
            ),
        ),
    ]
