# Generated by Django 4.2.6 on 2023-10-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.CharField(default="/", max_length=255),
        ),
    ]
