# Generated by Django 4.2.6 on 2023-11-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "permissions": [
                    ("can_view_books", "Can view books"),
                    ("can_view_authors", "Can view authors"),
                    ("can_checkout_book", "Can checkout book"),
                    ("can_add_books", "Can add books"),
                    ("can_update_books", "Can update books"),
                    ("can_delete_books", "Can delete books"),
                    ("can_add_authors", "Can add authors"),
                    ("can_update_authors", "Can update authors"),
                    ("can_delete_authors", "Can delete authors"),
                    ("can_view_bookloans", "Can view bookloans"),
                    ("can_add_bookloans", "Can add bookloans"),
                    ("can_update_bookloans", "Can update bookloans"),
                    ("can_delete_bookloans", "Can delete bookloans"),
                ]
            },
        ),
    ]
