# Generated by Django 4.2.6 on 2023-11-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userprofile_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={},
        ),
    ]
